# Generated by Django 3.2.18 on 2023-05-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='latitude',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='longitude',
            field=models.FloatField(default=None, null=True),
        ),
    ]
